# 均可使用RPG 里的变量 VIP 称号
Boss血条:
  default:
    是否开启: true
    是否根据玩家血量变化: true
    消息轮播:
      - "称号 {ch} 金钱 {money}"
    间隔时间: 5
  world:
    是否开启: true
    是否根据玩家血量变化: true
    消息轮播:
      - "称号 {ch} 金钱 {money}"
    间隔时间: 5
头部:
  default:
    是否开启: true
    显示: "{vip} ✤ {ch} ✤ {name} - {ms}\n§c❤ {m}/{mh}"
  world:
    是否开启: true
    显示: "{vip} ✤ {ch} ✤ {name} - {ms}\n§c❤ {m}/{mh}"
聊天:
  default:
    是否开启: true
    是否仅在世界内有效: false
    显示: "§7[§a{levelName}§7]§4[§6▶§f{ch}§4]§2[§cVIP♥§f{vip}§2]{name} §b>>> {msg}"
  world:
    是否开启: true
    是否仅在世界内有效: false
    显示: "§7[§a{levelName}§7]§4[§6▶§f{ch}§4]§2[§cVIP♥§f{vip}§2]{name} §b>>> {msg}"
底部:
  default:
    是否开启: true
    # 0 : tip 1: popup 2:actionBar
    显示类型: 0
    显示: "§c✎手持>{id}:{damage}  §9☣地图>{levelName}  §d♨生命>{h}/{mh}  §f۞在线>{online}/{maxplayer}  §b❉延迟>{ms} \n §2✤称号>{ch}
                 \  §e♈金币>{money}   §7☼时间>{时}:{分}:{秒}  §3❤坐标>x: {x} y: {y} z: {z}"
  world:
    是否开启: true
    # 0 : tip 1: popup 2:actionBar
    显示类型: 0
    显示: "§c✎手持>{id}:{damage}  §9☣地图>{levelName}  §d♨生命>{h}/{mh}  §f۞在线>{online}/{maxplayer}  §b❉延迟>{ms} \n §2✤称号>{ch}
               \  §e♈金币>{money}   §7☼时间>{时}:{分}:{秒}  §3❤坐标>x: {x} y: {y} z: {z}"

计分板:
  default:
    是否开启: true
    Title: "Server Name"
    Line:
      - "§6☼§r当前模式: {gm}"
      - "§6☼§r当前权限: {op}"
      - "§6☼§r飞行状态: {fly}"
      - "§6☼§r饥饿度: {food}/{mfood}"
  world:
    是否开启: true
    Title: "Server Name"
    Line:
      - "§6☼§r当前模式: {gm}"
      - "§6☼§r当前权限: {op}"
      - "§6☼§r飞行状态: {fly}"
      - "§6☼§r饥饿度: {food}/{mfood}"
变量显示:
  无称号显示: "§c无称号"
  无VIP显示: "§c无VIP"
  无公会显示: " c无公会"
  无结婚显示: "§c单身"
  玩家权限:
    op: "§c[§e管理员§c]§f"
    player: "§c[§a玩家§c]§f"
  游戏模式:
    "0": "生存"
    "1": "创造"
    "2": "冒险"
    "3": "旁观"
  飞行:
    "0": "飞行开启"
    "1": "飞行关闭"

自定义刷新刻度:
  计分板: 20
  底部: 20
  头部: 20
  Boss血条: 20


自定义指令:
  name: tips
  aliases:
    - 底部
  description: 自定义玩家提示

