name: Tips
main: tip.Main
version: 1.8.6
api: ["1.0.8"]

load: POSTWORLD


permissions:
  tips.ts:
    description: "设置GUI"
    default: true
  tips.me:
    description: "设置自身的显示"
    default: op
  tips.theme:
    description: "设置自身的显示样式"
    default: true